name: Deploy

on:
  push:
    branches: [master]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo -n -e "2.1" > text.txt
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: text.txt
      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "action_state=yellow" >> $GITHUB_ENV
      - run: echo $action_state
      - run: echo "Hi from the future"
      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          set_commits: auto
          version: "2.1"
